import numpy as np
import numpy.typing as npt

Returns = npt.NDArray[np.float64]

def cum_returns(returns: Returns) -> npt.NDArray[np.float64]: ...
def vol(returns: Returns, precision: int) -> float: ...
def max_dd(returns: Returns, precision: int) -> float: ...
def max_dd_threshold_position(
    returns: Returns, precision: int, threshold: float
) -> npt.NDArray[np.float64]: ...
