# Generated by Django 3.0.2 on 2020-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_returns_xrusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='bill_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='returns',
            name='bond_tr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='returns',
            name='cpi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='returns',
            name='eq_tr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='returns',
            name='xrusd',
            field=models.FloatField(),
        ),
    ]
