# Generated by Django 3.0.2 on 2020-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_realreturns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
