# Generated by Django 3.0.2 on 2020-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_coverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundCoverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="StockCoverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("ticker", models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name="Coverage",
            new_name="IndexCoverage",
        ),
    ]
