# Generated by Django 3.0.8 on 2021-01-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_undoing"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RealReturns",
        ),
    ]
