# Generated by Django 3.0.8 on 2021-04-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_auto_20210127_1838"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorReturns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor", models.CharField(max_length=10)),
                ("ret", models.FloatField()),
                ("name", models.CharField(max_length=50)),
                ("period", models.CharField(max_length=50)),
            ],
        ),
    ]
