# Generated by Django 3.0.8 on 2021-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_factorreturns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factorreturns",
            name="id",
        ),
        migrations.AddField(
            model_name="factorreturns",
            name="period_name",
            field=models.CharField(
                default="default",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
