# Generated by Django 3.0.8 on 2021-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_secfilingpaths_secformid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecIssuerId",
            fields=[
                ("issuer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("issuer_name", models.CharField(max_length=200)),
            ],
        ),
    ]
