# Generated by Django 3.0.8 on 2021-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_secissuerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secformid',
            name='form_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
