# Generated by Django 3.0.8 on 2021-11-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_thirteenfposition_cusip"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="thirteenfposition",
            unique_together={("issuer_id", "filing_date")},
        ),
    ]
